language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get install -qq gfortran python-dev python-numpy python-scipy python-suds python-lxml python-sqlalchemy python-m2crypto
  - pip install https://github.com/yarikoptic/coveralls-python/archive/master.zip
  - pip install geographiclib
  - pip install --use-mirrors matplotlib==1.3.0
  - pip install --use-mirrors flake8
install:
  - git remote add obspy git://github.com/obspy/obspy.git
  - git fetch obspy --tags
  - git fetch origin --tags
  - DEPTH=300; while [ "$(git describe 2> /dev/null)" == "" ]; do DEPTH=$(($DEPTH+200)); git fetch origin --depth=$DEPTH --quiet; done # continue fetching more older commits until git describe is able to reach the last tagged version
  - git status
  - pip install --use-mirrors .
  - git status
script:
  # We change directories to make sure that python won't find the copy
  # of obspy in the source directory, see 
  # https://github.com/numpy/numpy/blob/master/.travis.yml#L44
  - mkdir empty
  - cd empty
  - MODULELIST=`python -c "from obspy.core.util import DEFAULT_MODULES as MODULES; print 'obspy.' + ',obspy.'.join(MODULES)"`
  - coverage run --source=$MODULELIST -m obspy.core.scripts.runtests -n travis-ci -r --keep-images
after_success:
  - coveralls
notifications:
    email: false
# Upload any potentially produced diffs and produced images to imgur after a test failure.
after_failure:
  - cd
  - wget "http://imgur.com/tools/imgurbash.sh"
  - for FILE in `find . -regex '.*/tests/images/testrun/.*png' | sort`; do echo $FILE; bash imgurbash.sh $FILE; done
