# We pretend to be erlang because we can't use the python support in travis-ci
# see also: https://groups.google.com/forum/#!msg/travis-ci/uJgu35XKdmI/CctnUkYnEJEJ
language: erlang
before_install:
  - lsb_release -a  # get info on the operating system
  - sudo apt-get install -qq gfortran python python-dev python-setuptools python-numpy python-scipy python-matplotlib python-suds python-lxml python-sqlalchemy 1> /dev/null  # install dependencies
  - git remote add obspy git://github.com/obspy/obspy.git
  - git fetch obspy --tags
  - git fetch origin --tags
  - DEPTH=300; while [ "$(git describe 2> /dev/null)" == "" ]; do DEPTH=$(($DEPTH+200)); git fetch origin --depth=$DEPTH --quiet --tags; done  # continue fetching more older commits until git describe is able to reach the last tagged version
  - git describe
install:
  - sudo python setup.py -q install
  - python -c "import obspy; print obspy.__version__"
  - cd /usr/local/lib/python2.7/dist-packages/obspy-*; git rev-parse --show-toplevel
script:
  - sudo obspy-runtests -n travis-ci -r
notifications:
    email: false
